[package]
name = "petstore"
version = "0.1.0"
authors = ["Clayton Spinner <clayton.spinner@gmail.com>"]

[dependencies]
iron = "0.4.*"
router = "*"
urlencoded = "0.4.1"
rustc-serialize = "*"
log = "*"
slog = "1.3.2"
slog-term = "1.3.3"

[[bin]]
name = "main"
doc = false